### ISSUE TITLE
How to guess ？

### ISSUE THREAD

**Issue by 8427003** [DubFriend/guess-indent#1]
I can't find the rule to guess in sublime' doc.  i see your rule is:

```
 if stats.tabIndentCount >= stats.spaceIndentCount and stats.tabIndentCount >= 2
          editor.setSoftTabs false
          editor.setTabLength defaultTabLength
        else if stats.tabIndentCount < stats.spaceIndentCount and stats.frequency >= 2
          editor.setSoftTabs true
          editor.setTabLength(stats.mostCommonTabLength or defaultTabLength)
        else
          editor.setSoftTabs defaultIsSoftTabs
          editor.setTabLength defaultTabLength
```
# question 1：

```
stats.tabIndentCount >= 2  // why 2 ?

stats.frequency >= 2 //why 2?
```
# question 2:

are you sure that the rule is the same as sublime's rule. can you give me the doc by sublime if you have one?  I'm studying editor indent , need your help, thank!

**Comment by DubFriend** [comment]
I did not use the sublime rules when creating guess-indent, but the behavior is similar to sublime text's guess indent feature.

```
stats.tabIndentCount >= 2  // why 2 ?
stats.frequency >= 2 //why 2?
```

These values are somewhat arbitrary. The idea is that guess-indent will not change indentation settings, unless it can find at least 2 lines of indented code in the file.  This is to prevent guess-indent from applying rules to very short files. 

Additionally, guess-indent will not apply its settings if the indent size is found to be less than 2 spaces.

You would probably not want to set an indent rule based on this one line of code.

Also I like your Avatar :smile:

**Comment by 8427003** [comment]
thank, close the issue, :smile:  !
